### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by taeguk** [fobabs/ubuntu-terminal#1]
Hello, I looked [one article](https://dev.to/fobabs/how-i-built-a-typical-ubuntu-terminal-using-html-css-1bpj) written by you.
It's so awesome. It looks like ubuntu really.
Could I utilize all or some part of codes to make my personal homepage?

**Comment by fobabs** [comment]
Yes, you can. It's completely free for use.

**Comment by fobabs** [comment]
> Hello, I looked [one article](https://dev.to/fobabs/how-i-built-a-typical-ubuntu-terminal-using-html-css-1bpj) written by you.
> 
> It's so awesome. It looks like ubuntu really.
> 
> Could I utilize all or some part of codes to make my personal homepage?

Yes, you can utilize all. It's completely free for use.

**Comment by taeguk** [comment]
Thanks! It's my website to use your codes: https://taeguk.github.io/
